fffffffffffffffkkkkkkkkk

diff --git a/vdt_start b/vdt_start
--- a/vdt_start
+++ b/vdt_start
@@ -6,16 +6,14 @@
 
 
 # TODO: Add filesystem shortcuts to desktop.
-VDT_HOME=${VDT_HOME:-"$HOME/.vdt"}
-VDT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-VDT_LOCKFILES=${VDT_LOCKFILES:-"$VDT_ROOT/lockfiles"} 
-VDT_TEMPLATES=${VDT_TEMPLATES:-"$VDT_ROOT/templates"}
 
-max_desktops=3;
+initialize(){
+    export VDT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+    source "${VDT_ROOT}/utils/common.sh"
+    minport=1024
+    maxport=65536
+}
 
-module purge > /dev/null  2>&1
-module load Python Singularity/3.6.1 -q 
-module unload XALT/NeSI -q
 
 help() {
 cat << EndOfHelp
@@ -59,7 +57,7 @@ parse_input() {
     while true;do
         case $1 in
             -v|--verbose)
-                verbose="-v"
+                export verbose="-v"
                 #set -x
                 shift
             ;;
@@ -72,7 +70,7 @@ parse_input() {
                 shift
             ;;
             -p|--persistent)
-                echo "persistant containers currently disabled"
+                echo "Persistent containers are still in development. Use caution"
                 #exit 1 
                 persistent="&"
                 shift
@@ -114,11 +112,11 @@ parse_input() {
             ;;
             *)  
                 if [[ $# -eq 1 ]];then
-                    if (($1 < 2));then
-                        echo "Port number must be larger than 1.";exit 1
-                    elif (($1 > 65535));then
-                        echo "Port number must be less than 65536.";exit 1
-                    else (($1 >= 1 && $1 <= 65535))
+                    if (($1 < $minport));then
+                        echo "Port number must be larger than $minport.";exit 1
+                    elif (($1 > $maxport));then
+                        echo "Port number must be less than $maxport.";exit 1
+                    else
                         VDT_SOCKET_PORT="$1";break
                     fi
                 fi
@@ -132,40 +130,49 @@ parse_input() {
             ;;
         esac
     done
-    if ls ${VDT_LOCKFILES}/*${remote:-$(hostname)}:${VDT_SOCKET_PORT} 1> /dev/null 2>&1;then echo "Socket port '${VDT_SOCKET_PORT}' is in use on ${remote:-$(hostname)}, please choose another.";return 1;fi    
+    if ls ${VDT_LOCKFILES}/*${remote:-$(hostname)}:${VDT_SOCKET_PORT} 1> /dev/null 2>&1;then echo "WARNING: Socket port '${VDT_SOCKET_PORT}' is in use on ${remote:-$(hostname)}, you may have to choose another.";return 0;fi    
 
     # Create directory for logs, certificates etc
     mkdir -p "${VDT_HOME:="${HOME}/.vdt"}"
 
     # Select template.
     if [[ -z "${VDT_BASE}" ]];then VDT_BASE="default";fi
+
     if (ls ${VDT_TEMPLATES}/${VDT_BASE} > /dev/null); then
-        echo "Using '${VDT_BASE}' as template."
+        echo "Using '${VDT_BASE}' as template."       
     else
         echo "Unknown template '${1}', valid options are '$(ls ${VDT_TEMPLATES})'.\n"
+    fi
+    
+    # Get node from env if slurm id set.
+    #vecho "Destination is '${remote}', Current host '$(hostname)'"
+    if [[ -n "$SLURM_JOB_ID" && -z "${remote}" ]]; then
+        remote=$(echo $SLURM_NODELIST | sed -E 's/^([a-z]{3})\[+([0-9]{3}).*/\1\2/') 
+        #echo "Remote: '${remote}', Hostname: '$(hostname)'"
+        if [[ "$remote" != "$(hostname)" && -z "${remote}" ]];then # Need to test again to avoid printing twice.
+            echo "Connection will be forwarded to $remote. Run 'unset SLURM_JOB_ID' if this isn't what you want."
+        fi
     fi
 
     # Create name.
     VDT_INSTANCE_NAME=${_instance_name:-"${VDT_BASE}_${USER}"}
      # Set logfiles dest
-    vecho "${VDT_LOGFILE:="${VDT_HOME}/${VDT_INSTANCE_NAME}.${remote:-$(hostname)}:${VDT_SOCKET_PORT}.log"}"
-    touch "${VDT_LOGFILE}"
-    vecho "logfile is ${VDT_LOGFILE}"
+    touch "${VDT_LOGFILE:="${VDT_HOME}/${VDT_INSTANCE_NAME}.${remote:-$(hostname)}:${VDT_SOCKET_PORT}.log"}"
+    vecho "Logfile is ${VDT_LOGFILE}"
 
     # If clean flag exists remove cache.
+
+    #Sanitise
+    VDT_INSTANCE_NAME=${VDT_INSTANCE_NAME//[^a-zA-Z0-9_]/}
     while true; do
-        if ! ls "${VDT_LOCKFILES}"/*"${VDT_INSTANCE_NAME}"* 1> /dev/null 2>&1;then echo "Instance name: ${VDT_INSTANCE_NAME}";break;fi
-        export VDT_INSTANCE_NAME="${VDT_INSTANCE_NAME}_new";    
+        if ! ls "${VDT_LOCKFILES}"/*"${VDT_INSTANCE_NAME}"\..* 1> /dev/null 2>&1;then break;fi
+        p2=$(($(echo ${VDT_INSTANCE_NAME} | grep -Eo '[0-9]+$' || echo 0)+1))
+        p1="$(echo ${VDT_INSTANCE_NAME} | grep -Eo '.*_[^0-9]')"
+        echo "$p2"
+        echo "$p1"
+        export VDT_INSTANCE_NAME="${p1}_${p2}"   
     done   
 
-    # Get node from env if slurm id set.
-    #vecho "Destination is '${remote}', Current host '$(hostname)'"
-    if [[ -n "$SLURM_JOB_ID" && -z "$remote" ]]; then
-        remote=$(echo $SLURM_NODELIST | sed -E 's/^([a-z]{3})\[+([0-9]{3}).*/\1\2/')
-        if [[ "$remote" != "$(hostname)" ]];then
-        echo "Connection will be forwarded to $remote. Run 'unset SLURM_JOB_ID' if this isn't what you want."
-        fi
-    fi
     # if [[ -z "$session_jobid" && -n "$SLURM_JOB_ID" ]]; then
     #     printf "'SLURM_JOB_ID' set. Connection will be forwarded to job $SLURM_JOB_ID.\n"
     #     export session_jobid="$SLURM_JOB_ID"
@@ -177,165 +184,110 @@ parse_input() {
     #find "$VDT_LOCKFILES" -type f -user "$(whoami)" -name *${1}* -exec rm ${verbose} -f {} \;
 }
 
-ssh_forward(){
+launch(){
     # If remote destination is set, and not self.
-    if [[ -n $remote ]] && [[ ! $remote == $(hostname) ]];then
-        echo "Forwarding to ${remote}..."
-
+    if [[ -n $remote ]];then
+        cmd1="ssh ${verbose} -A -o StrictHostKeyChecking=no -o ExitOnForwardFailure=yes ${remote}"
         # If ephemeral, local forwarding is good. 
         if [[ -z $persistent ]];then
-            localforward="-L ${VDT_SOCKET_PORT}:localhost:${VDT_SOCKET_PORT}"
-        else
-            export VDT_TUNNEL_HOST="$(hostname)"
-            env_fwd="export VDT_TUNNEL_HOST=$(hostname) && "
+            cmd1="$cmd1 -L ${VDT_SOCKET_PORT}:localhost:${VDT_SOCKET_PORT}"
+        else #add this hostname.
+            VDT_TUNNEL_HOST="$(hostname)"
         fi
-        vex ssh ${verbose} -A -o StrictHostKeyChecking=no -o ExitOnForwardFailure=yes ${localforward} "${remote}" "${env_fwd}${VDT_ROOT}/vdt_start" "${args[@]:0}"
-        # Take original arguments
-        exit $?
-    fi
-  
-}
-set_env(){
-    if [[ -n $clean ]];then
-        "${VDT_ROOT}/clean_env"
-    fi
-    if [[ -n $secure ]];then
-        # If environment setup for desktop flavor.
-        echo "Generating security certificate."
-        if [[ ! -f "${VDT_HOME}/self.pem" ]];then
-            openssl req -new -x509 -days 365 -nodes -subj "/C=NZ/ST=Wellington/L=Wellington/O=NeSI/CN=$(hostname)" -out "${VDT_HOME}/self.pem" -keyout "${VDT_HOME}/self.pem"
-        fi    
-        VDT_WEBSOCKOPTS="$VDT_WEBSOCKOPTS --cert=${VDT_HOME}/self.pem"
-    fi
-
-    set_display "$_display_port"
-
-    export SINGULARITY_BINDPATH="\
-/run,\
-/etc/machine-id,\
-/opt/nesi,\
-/nesi/project,\
-/nesi/nobackup,\
-/usr/share/lmod/lmod,\
-/etc/opt/slurm,\
-/opt/slurm,\
-/usr/lib64/libmunge.so,\
-/usr/lib64/libmunge.so.2,\
-/usr/lib64/libmunge.so.2.0.0"
-
-    vecho "Singularity bindpath is $(echo "${SINGULARITY_BINDPATH}" | tr , '\n')"
-
     
-    # If environment setup for desktop flavor.
-    if [[ -f "${VDT_TEMPLATES}/${VDT_BASE}/pre.sh" ]];then
-        source "${VDT_TEMPLATES}/${VDT_BASE}/pre.sh" 
-    fi
-
-    # Export all variables starting with 'VDT' to singularity.
-    for ev in $(compgen -A variable | grep ^VDT );do
-        export "SINGULARITYENV_$ev"="${!ev}"
-        vecho "SINGULARITYENV_$ev=${!ev}"
-    done
-    
-    # Murder any ports that were missed.
-    while [[ "$(fuser "$VDT_SOCKET_PORT"/tcp 2>/dev/null | wc -w)" -gt 0 ]];do
-        echo "Port '$VDT_SOCKET_PORT' in use. Killing $VDT_SOCKET_PORT"
-        kill -9 $(fuser "$VDT_SOCKET_PORT"/tcp 2>/dev/null | awk '{ print $1 }')
-    done
-}
-
-create_vnc(){   
-    # Set instance name
-    if [[ ! -x  "$(readlink -f "$VDT_TEMPLATES/$VDT_BASE/image")" ]];then echo "'$VDT_TEMPLATES/$VDT_BASE/image' doesn't exist!";exit 1;fi
-
-    img_path=$(readlink -f "$VDT_TEMPLATES/$VDT_BASE/image")
-    touch "${lockfile}"
-    fullcmd="${timeout}" singularity "${verbose}" run "${nohome}" "${img_path}"
-    if [[ -n $persistent ]];then
-        instance 
     else
-        vex "$fullcmd" 
+        cmd1="bash -c"
     fi
-}
-
-daemon(){
-    # chdir("/")                     || die "can't chdir to /: $!";
-    # open(STDIN,  "<", "/dev/null") || die "can't read /dev/null: $!";
-    # open(STDOUT, ">", "/dev/null") || die "can't write /dev/null: $!";
-    # defined(my $pid = fork())      || die "can't fork: $!";
-    # exit if $pid;              # non-zero now means I am the parent
-    # (setsid() != -1)           || die "Can't start a new session: $!";
-    # open(STDERR, ">&", STDOUT) || die "can't dup stdout: $!";
-
-    # setsid myscript.sh >/dev/null 2>&1 < /dev/null &
-
-    sleep 30
-    echo "TESTING"
-    exit 0
-    # vex "$fullcmd"
-    # vex "${timeout}" singularity "${verbose}" instance start "${nohome}" "${img_path}" "${VDT_INSTANCE_NAME}" 
-    # img_path="instance://${VDT_INSTANCE_NAME}"
-    # sleep 3
-    # printf "Desktop %s started\n" "${VDT_INSTANCE_NAME}"
-    # printf "Connect at: http://localhost:%s  \nKill with: vdt kill %s" "${VDT_SOCKET_PORT}" "${VDT_INSTANCE_NAME}"
-}
-
-set_display (){
-    #Finds a free display port. If passed an argument, will test that then return.
-    max_i=4;
-    for (( i=0; i<max_i; i++ )); do
-        VDT_DISPLAY_PORT=${1:-$(shuf -i 1100-2000 -n 1)}
-        if [[ ! -e "/tmp/.X11-unix/X{$VDT_DISPLAY_PORT}" ]];then return 0;fi
-        if [[ $# -gt 0 ]];then echo "Selected display port ${1} not suitable."; return 2;fi
+    # Export all variables starting with 'VDT' to singularity.
+    startcmd="export"
+    for ev in $(compgen -A variable | grep ^VDT );do
+        startcmd="$startcmd $ev=\"${!ev}\""
     done
-    echo "Could not find a suitable display port after $max_i attempts."; return 1
+    # if [[ -n ${verbose} ]];then
+    #     startcmd="$startcmd verbose=-v"
+    # fi
+    startcmd="${startcmd} && ${VDT_ROOT}/utils/singularity_wrapper.sh"
+    printf "Launching on %s..." "${remote}"
+    if [[ -z $persistent ]];then
+        #echo "Starting ephemeral desktop on $msg"
+        printf "\r\033[0KLaunch Successful\n" 
+        startcmd=''${cmd1}' "'$startcmd'"'
+        vecho "$startcmd"
+        eval "$startcmd"
+    else 
+        startcmd='nohup '${cmd1}' "'$startcmd'" >> '$VDT_LOGFILE' 2>&1 &'
+        vecho "$startcmd"
+        eval "$startcmd"
+        echo "$!" > "${lockfile}" 
+        printf "\r\033[0KLaunch Successful\n" 
+        if [[ -n $remote ]];then
+            assert_lennut
+        fi
+        assert_pid
+        #echo "PID is '${daemon_pid}'"
+        echo ""
+        echo "Instance name: '${VDT_INSTANCE_NAME}'"
+        echo "Logfile is '${VDT_LOGFILE}'"
+        echo "Connect with 'http://localhost:${VDT_SOCKET_PORT}'"
+        exit 0
+    fi
 }
 
-vecho () {
-    # For verbose print.
-    if [[ $verbose ]]; then
-        echo "$LINENO:$*"
-    fi
-    echo "$LINENO:$*" >> "$VDT_LOGFILE"
-}
+# assert_per(){
+#     # If was -p. This is the end of the script.
+#     if [[ -n $persistent ]];then
+#         assert_lennut
+#         assert_vnc
+#         assert_pid
+#         #echo "PID is '${daemon_pid}'"
+#         echo ""
+#         echo "Instance name: '${VDT_INSTANCE_NAME}'"
+#         echo "Logfile is '${VDT_LOGFILE}'"
+#         echo "Connect with 'http://localhost:${VDT_SOCKET_PORT}'"
+#         exit 0
+#     fi
+# }
 
-vex () {
-    # For verbose execute.
-    if [[ $verbose ]]; then
-        echo "$LINENO:$*"
+assert_pid(){
+    printf "Checking proceesses are running on %s..." "${remote:-$(hostname)}"
+    if [[ -n ${remote} ]];then
+        cmd="ssh ${verbose} ${remote} "
     fi
-    echo "$LINENO:$*" >> "$VDT_LOGFILE"
-    $@
+    cmd="${cmd}${VDT_ROOT}/utils/check_pid.sh"
+    if $cmd > vecho 2>&1;then 
+        printf "\r\033[0KFound all proceesses.\n"
+    else
+        printf "\r\033[0KError: VDT did not launch properly on node.\n" 
+        exit 1
+    fi
+}
+assert_vnc(){
+
+    return 0
+
+}
+assert_lennut(){
+    printf "Looking for tunnel to %s..." "${remote}"
+    max_test_lennut=4
+    for (( i=0; i<$max_test_lennut; i++ )); do
+        sleep 4
+        if [ ! $(netstat -tpln 2>vecho | grep -P "^tcp\s*\d*\s*\d*\s*127.0.0.1:${VDT_SOCKET_PORT}.*$" > vecho 2>&1) ];then
+            printf "\r\033[0KTunnel Live.\n"
+            return 0
+        fi
+        vecho "Could not find tunnel. Attempt ($i/$max_test_lennut)"
+    done 
+    printf "\r\033[0KError: Could not find tunnel after %s attempts." "${max_test_lennut}\n"
+    return 1
 }
 
 main() {
+    initialize
     parse_input "$@"
-    ssh_forward 
-    set_env
-    create_vnc
-    
-    return 0
+    launch 
+    return $?
 }
-cleanup() {
-    #vncserver
-    singularity $verbose exec "$img_path" "vncserver -kill ":$VDT_DISPLAY_PORT"" 1> ${VDT_LOGFILE} 2>&1 || true
-    rm -f $verbose /tmp/.X11-unix/.X*
-    rm -f $verbose "$HOME"/.vnc/*"${VDT_INSTANCE_NAME}".pid
 
-    if [[ -n "${VDT_LOGFILE}" ]]; then rm -f $verbose "${VDT_LOGFILE}";fi
-    if [[ -n "${lockfile}" ]]; then rm -f $verbose "${lockfile}";fi
-    # Unset all VDT variables.
-    for ev in $(compgen -A variable | grep ^VDT );do
-        unset "$ev"
-    done
-    pkill --signal 9 -P $$ > /dev/null 2>&1 
-    
-    #rm -f "/tmp/.X$display_port-lock"
-    return 0
-    # while [[ "$(fuser $1/tcp 2>/dev/null | wc -w)" -gt 0 ]];do
-    #     kill -9 "$(fuser $1/tcp 2>/dev/null | awk '{ print $1 }')"
-    # done
-}
 # construct_ssh() {
 #     # If jobid is specified, get host of jobid.
 #     if [[ "$session_jobid" ]];then
@@ -376,7 +328,36 @@ cleanup() {
 #         return 1
 #     fi
 # }
-trap cleanup INT
 
-main "$@"
+cleanup() {
+    #vncserver
+    #singularity $verbose exec "$img_path" "vncserver -kill ":$VDT_DISPLAY_PORT"" 1> ${VDT_LOGFILE} 2>&1 || true
+    #rm -f $verbose /tmp/.X11-unix/.X*
+    #rm -f $verbose "$HOME"/.vnc/*"${VDT_INSTANCE_NAME}".pid
+    echo "Trapped $?"
+    #if [[ -n "${VDT_LOGFILE}" ]]; then rm -f $verbose "${VDT_LOGFILE}";fi
+    if [[ -n "${lockfile}" ]]; then rm -f $verbose "${lockfile}";fi
+    # Unset all VDT variables.
+    for ev in $(compgen -A variable | grep ^VDT );do
+        unset "$ev"
+    done
+    
+    rm -fvr "/tmp/.X$display_port-lock"
+    rm -fvr "/tmp/.ICE$display_port-lock"
 
+    while [[ "$(fuser $VDT_SOCKET_PORT/tcp 2>/dev/null | wc -w)" -gt 0 ]];do
+        kill -9 "$(fuser $VDT_SOCKET_PORT/tcp 2>/dev/null | awk '{ print $1 }')"
+    done
+
+    pkill --signal 9 -P $$ > /dev/null 2>&1 
+
+    return 1
+
+}
+cleanup_nice(){
+    return 0
+}
+
+trap cleanup INT ERR SIGINT SIGTERM
+
+main "$@" || cleanup && cleanup_nice
